Update Ruby to 2.2.8
sky-uk/colonel pull request #7
Opened 2017-10-31 10:29 UTC by benjy2429

https://github.com/sky-uk/Digital-Help/issues/1292

This upgrades Ruby and RubyGems out of a security vulnerability. Ruby is now on the lowest patched version - `2.2.8`.

As part of this, I've also updated the provisioning scripts to support Ansible 2.0.

All existing tests are passing in the Vagrant box.

### To QA

* Run the Vagrant box:
  * `vagrant up`
  * `vagrant ssh`
  * `cd /vagrant`
* Run test suites:
  * `bundle exec rspec`
  * `bundle exec cucumber`

### To release

* Merge into master
* Create a new tag:
  * `git tag v0.8.4`
  * `git push origin --tags`
* Merge PRs in help-cms and image-hub

2017-10-31 12:17 UTC, smnalex requested changes

2017-10-31 12:17 UTC, smnalex commented on Gemfile
> +ruby '2.2.8'
Can we update ruby to 2.3.5 as 2.2.8 `will EOL soon!` https://www.ruby-lang.org/en/downloads/

2017-10-31 13:07 UTC, smnalex approved these changes

2017-11-07 09:19 UTC, lukedh commented
QA'd by running the review above with all tests passing. 
This is now ready to deploy once we are out of change freeze.

2017-11-08 12:05 UTC, merged